fix unicode encode error on `quilt ls` and `quilt inspect` on Python 2.7 (#165)
For python 2.7, you will get a unicode encode error like this
```
Traceback (most recent call last):
  File "/usr/local/bin/quilt", line 11, in <module>
    load_entry_point('quilt==2.7.0', 'console_scripts', 'quilt')()
  File "/usr/local/lib/python2.7/dist-packages/quilt/tools/main.py", line 138, in main
    func(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/quilt/tools/command.py", line 799, in ls
    print("%s%s/%s" % (unicode(prefix), owner, pkg))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
```
because print can't handle a unicode

simplest repro:
```py
prefix = u"└── "
print prefix
# vs
print prefix.encode('utf-8')
```